version: '3.7'
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus-native
    volumes:
      -  /etc/localtime:/etc/localtime:ro
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana

volumes:
  grafana-data:
