global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'spring-boot-app-native-image'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 15s
    static_configs:
      - targets: ['host.docker.internal:8080']
  - job_name: 'spring-boot-app-jar'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 15s
    static_configs:
      - targets: [ 'host.docker.internal:8081' ]

